Webrouse com 596 update guzzle auth
keboola/generic-extractor pull request #139
Opened 2021-01-21 12:31 UTC by webrouse

2021-01-21 13:19 UTC, webrouse commented on tests/phpunit/Authentication/LoginTest.php
>  class LoginTest extends ExtractorTestCase
Pre lepsie pochopenie pozri `LoginTest.php`.

2021-01-21 13:19 UTC, webrouse commented on src/Authentication/AuthInterface.php
> +    public function attachToClient(RestClient $client): void;
Pre lepsie pochopenie pozri `BasicTest.php`.

2021-01-21 13:19 UTC, webrouse commented on src/Authentication/Query.php
> +                    Utils::mergeQueries($uri->getQuery(), $authQuery)
Pre lepsie pochopenie pozri `QueryTest.php`.

2021-01-21 13:19 UTC, webrouse commented on composer.json
> -            "@phpstan",
Phpstan som musel zatial vypnut, ako som aktualizoval balicky a kod, ktory som este nerefactoroval uz nie je kompatibilny.

2021-01-22 07:01 UTC, ondrajodas commented
dneska na to kouknu

2021-01-25 08:18 UTC, ondrajodas requested changes

2021-01-25 08:24 UTC, webrouse commented on composer.json
> +        "keboola/juicer": "dev-webrouse-COM-596-update-guzzle",
@ondrajodas ano, to je naschval, kedze sa este nemerguje do mastra. Na tu dev vetvu sa spravi review na koniec, kedze som aj tam musel postupne fixovat nejake veci.

Tu je PR, a pri kazdom PR som musel nejake drobnosti menit, takze to nemalo zmysel spravit este dalsich 5PR tam, ale az na koniec to doriesit:
https://github.com/keboola/juicer/pull/37

2021-01-25 08:37 UTC, ondrajodas commented on composer.json
> +        "keboola/juicer": "dev-webrouse-COM-596-update-guzzle",
nj, nevšiml jsem si že to není do masteru :)

2021-01-25 08:37 UTC, ondrajodas approved these changes
ok

2021-01-25 08:37 UTC, merged