Fix/test request sync action
keboola/generic-extractor pull request #194
Opened 2024-12-05 14:01 UTC by AlbSed

in the end just a freeze of requirements

2024-12-05 14:35 UTC, ZdenekSrotyr requested changes

2024-12-05 14:35 UTC, ZdenekSrotyr commented on python-sync-actions/requirements.txt
> +keboola.utils==1.1.2
použij 1.1.0  - 1.1.2 je Yunked

2024-12-05 14:43 UTC, AlbSed commented on python-sync-actions/requirements.txt
> +keboola.utils==1.1.2
done

2024-12-06 10:15 UTC, ZdenekSrotyr approved these changes
lGTM

2024-12-06 15:21 UTC, merged